image: gitpod/workspace-postgres

tasks:
  - name: Init Ecommerce Project
    init: |
      chmod +x scripts/init_db.sh
      ./scripts/init_db.sh
    command: |
      echo "✅ Gitpod is ready. Visit Metabase at: https://3000-$(gp url 3000)"
