image: gitpod/workspace-full

tasks:
  - name: Setup Ecommerce DB
    init: |
      echo "⚙️ Starting init script..."
      chmod +x scripts/init_db.sh
      ./scripts/init_db.sh | tee init_output.log
    command: |
      echo "✅ Setup complete. Visit Metabase at: https://3000-$(gp url 3000)"
