version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ecommerce_db
      MB_DB_PORT: 5432
      MB_DB_USER: gitpod
      MB_DB_PASS: mypassword
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - metabase-data:/metabase-data

volumes:
  pgdata:
  metabase-data: